#eureka:
#  instance:
#    hostname: "${HOSTNAME}.eureka"
#  client:
#    register-with-eureka: false
#    fetch-registry: false
#    service-url:
#      defaultZone: ${EUREKA_SERVER_ADDRESS}

eureka:
  instance:
    hostname: eureka
  client:
    fetch-registry: false
    register-with-eureka: false

server:
  port: 8761