spring:
  application:
    name: NOTIFICATION-SERVICE
server:
  port: 8086

eureka:
  instance:
    prefer-ip-address: true
    hostname: eureka
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

#eureka:
#  instance:
#    prefer-ip-address: true
#    hostname: ${EUREKA_SERVER_HOSTNAME}
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: ${EUREKA_SERVER_ADDRESS}
