apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-service-app
  labels:
    app: frontend-service-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-service-app
  template:
    metadata:
      labels:
        app: frontend-service-app
    spec:
      containers:
        - name: frontend-service-app
          image: frontend-service
          imagePullPolicy: Never
          ports:
            - containerPort: 4200

---

apiVersion: v1
kind: Service
metadata:
  name: frontend-service-app
spec:
  selector:
    app: frontend-service-app
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 4200
