apiVersion: v1
kind: ConfigMap
metadata:
  name: eureka-server
data:
  eureka_server_hostname: eureka-0
  eureka_server_address: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service-app
  labels:
    app: gateway-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-service-app
  template:
    metadata:
      labels:
        app: gateway-service-app
    spec:
      containers:
        - name: gateway-service-app
          image: gateway-service
          imagePullPolicy: Never
          ports:
            - containerPort: 8084
          env:
            - name: EUREKA_SERVER_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  name: eureka-server
                  key: eureka_server_hostname
            - name: EUREKA_SERVER_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: eureka-server
                  key: eureka_server_address

---

kind: Service
apiVersion: v1
metadata:
  name: gateway-service-svc
spec:
  selector:
    app: gateway-service-app
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8084
