apiVersion: apps/v1
kind: Deployment
metadata:
  name: rating-service-app
  labels:
    app: rating-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rating-service-app
  template:
    metadata:
      labels:
        app: rating-service-app
    spec:
      containers:
        - name: rating-service-app
          image: rating-service
          imagePullPolicy: Never
          ports:
            - containerPort: 8083
          env:
            - name: EUREKA_SERVER_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  name: eureka-server
                  key: eureka_server_hostname
            - name: EUREKA_SERVER_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: eureka-server
                  key: eureka_server_address

---

kind: Service
apiVersion: v1
metadata:
  name: rating-service-svc
spec:
  selector:
    app: rating-service-app
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8083
